"""Measure the built AOI system in world space, frame by frame, inside Blender.

    blender -b -P hero/scripts/audit_aoi.py -- --scene hero_aoi_acquisition

``validate_hero.py`` checks the AOI *contract* from configuration without
Blender. This script checks the other half: that the geometry Blender actually
evaluates -- after parenting, Earth rotation, satellite animation and the beam
constraints -- still sits where the configuration says it should.

It answers three questions with numbers rather than opinion:

1. does every AOI vertex lie on the configured sphere, at every audited frame;
2. does each beam still start at the satellite and end on its AOI corner once
   the Earth has rotated and the camera has moved;
3. does the AOI keep one identity -- same corners, same orientation, same size --
   from global acquisition through regional approach.

Subjective questions (does it look attached to the planet, is the palette
right) are deliberately not answered here; those are what the rendered stills
are for.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import bpy  # noqa: E402
from mathutils import Vector  # noqa: E402

import aoi_system as ax  # noqa: E402
import build_scene  # noqa: E402
import hero_common as hc  # noqa: E402

# Tolerances.
#
# The geometry is generated by normalising unit vectors, so conformance is
# exact in exact arithmetic and the only real error is floating point. Blender
# evaluates object transforms in single precision, which carries ~1e-7 relative
# error; at an Earth radius of 6.371e6 m that is already ~0.6 m, and on a
# 1e7 m beam it is ~2 m. An absolute sub-metre tolerance would therefore be
# testing float32, not the implementation.
#
# So each tolerance is an absolute floor plus a relative term sized to that
# precision. These stay three or more orders of magnitude below any real
# registration defect -- a border that detached from the globe, or a beam aimed
# at the Earth centre or a stale corner, would miss by kilometres -- so the
# check still fails loudly on an actual regression.
RADIUS_TOLERANCE_FLOOR_M = 2.0
RADIUS_TOLERANCE_RELATIVE = 1.0e-6
BEAM_TOLERANCE_FLOOR_M = 5.0
BEAM_TOLERANCE_RELATIVE = 2.0e-6

M_PER_BU = ax.KM_PER_BLENDER_UNIT * 1000.0


def _evaluated(obj, depsgraph):
    return obj.evaluated_get(depsgraph)


def _world_vertices(obj, depsgraph):
    evaluated = _evaluated(obj, depsgraph)
    matrix = evaluated.matrix_world
    return [matrix @ vertex.co for vertex in evaluated.data.vertices]


def _fcurve_value(node_tree, socket, frame, default):
    """Evaluate a keyframed shader socket straight off its F-curve.

    Read from the curve rather than from the datablock so the number is the
    authored animation, independent of whether a background depsgraph has
    written evaluated values back.
    """
    animation = getattr(node_tree, "animation_data", None)
    action = getattr(animation, "action", None) if animation else None
    if not action:
        return default
    data_path = socket.path_from_id("default_value")
    for fcurve in build_scene._action_fcurves(action):
        if fcurve.data_path == data_path:
            return float(fcurve.evaluate(frame))
    return default


def audit(scene_id: str, fixture_id: str | None, frames) -> dict:
    spec = build_scene.build(scene_id, frame=None, aoi_fixture=fixture_id)
    scene_config = hc.load_scene_config()

    aoi_spec = next(
        (o for o in spec.get("objects", []) if o.get("type") == "aoi_system"), None
    )
    if aoi_spec is None:
        raise SystemExit("scene " + repr(scene_id) + " defines no aoi_system object")

    description = ax.describe(
        scene_config, fixture_id or aoi_spec.get("fixture"), spec
    )
    fixture = description["fixture"]
    earth_radius_km = description["earth_radius_km"]

    surface_radius_bu = description["surface_radius_bu"]
    lock_radius_bu = ax.surface_radius_bu(
        fixture, earth_radius_km, extra_offset_m=fixture["corner_lock_offset_m"]
    )

    prefix = aoi_spec["id"]
    expected_radius = {}
    for obj in bpy.data.objects:
        if obj.name == prefix + "_fill" or obj.name == prefix + "_border":
            expected_radius[obj.name] = surface_radius_bu
        elif obj.name.startswith(prefix + "_lock_"):
            expected_radius[obj.name] = lock_radius_bu

    corner_ids = list(description["corner_order"])
    targets = {cid: bpy.data.objects.get(prefix + "_target_" + cid) for cid in corner_ids}
    beams = {cid: bpy.data.objects.get(prefix + "_beam_" + cid) for cid in corner_ids}
    satellite = bpy.data.objects.get(
        aoi_spec.get("beams", {}).get("source_object_id", "satellite")
    )
    earth = bpy.data.objects.get(aoi_spec.get("parent_id", "earth"))

    missing = [name for name, obj in list(targets.items()) + list(beams.items()) if obj is None]
    if missing:
        raise SystemExit("AOI system did not build expected objects for: " + repr(missing))

    fill_material = None
    for material in bpy.data.materials:
        if material.use_nodes and material.node_tree.nodes.get("aoi_sweep_position"):
            fill_material = material
            break

    per_frame = []
    for frame in frames:
        bpy.context.scene.frame_set(int(frame))
        depsgraph = bpy.context.evaluated_depsgraph_get()

        worst_radius_m = 0.0
        worst_object = None
        vertex_count = 0
        for name, target_radius in expected_radius.items():
            obj = bpy.data.objects.get(name)
            if obj is None:
                continue
            for position in _world_vertices(obj, depsgraph):
                vertex_count += 1
                deviation = abs(position.length - target_radius) * M_PER_BU
                if deviation > worst_radius_m:
                    worst_radius_m = deviation
                    worst_object = name

        corner_radii_bu = {}
        target_world = {
            cid: _evaluated(obj, depsgraph).matrix_world.translation.copy()
            for cid, obj in targets.items()
        }

        for cid, position in target_world.items():
            corner_radii_bu[cid] = position.length

        satellite_world = _evaluated(satellite, depsgraph).matrix_world.translation.copy()
        beam_errors = {}
        for cid, beam in beams.items():
            matrix = _evaluated(beam, depsgraph).matrix_world
            tip = matrix @ Vector((0.0, 1.0, 0.0))
            root = matrix @ Vector((0.0, 0.0, 0.0))
            beam_errors[cid] = {
                "tip_to_corner_m": round((tip - target_world[cid]).length * M_PER_BU, 4),
                "root_to_satellite_m": round((root - satellite_world).length * M_PER_BU, 4),
                "length_km": round((tip - root).length * ax.KM_PER_BLENDER_UNIT, 3),
            }

        # Footprint identity: edge lengths and diagonals measured from the
        # evaluated corner targets. These must not drift as the shot proceeds.
        edges_km = []
        for index, cid in enumerate(corner_ids):
            following = corner_ids[(index + 1) % 4]
            a = target_world[cid].normalized()
            b = target_world[following].normalized()
            edges_km.append(math.acos(max(-1.0, min(1.0, a.dot(b)))) * earth_radius_km)

        centroid = Vector((0.0, 0.0, 0.0))
        for position in target_world.values():
            centroid += position
        centroid /= 4.0

        sweep_value = None
        if fill_material is not None:
            node = fill_material.node_tree.nodes.get("aoi_sweep_position")
            sweep_value = round(
                _fcurve_value(
                    fill_material.node_tree, node.outputs[0], frame, node.outputs[0].default_value
                ),
                5,
            )

        per_frame.append(
            {
                "frame": int(frame),
                "earth_rotation_z_deg": round(math.degrees(earth.rotation_euler.z), 4)
                if earth
                else None,
                "aoi_vertices_measured": vertex_count,
                "max_radius_deviation_m": round(worst_radius_m, 5),
                "max_radius_deviation_object": worst_object,
                "surface_clearance_m": round(
                    (
                        sum(corner_radii_bu.values()) / len(corner_radii_bu)
                        - earth_radius_km / ax.KM_PER_BLENDER_UNIT
                    )
                    * M_PER_BU,
                    3,
                ),
                "footprint_chord_sagitta_km": round(
                    (
                        sum(corner_radii_bu.values()) / len(corner_radii_bu) - centroid.length
                    )
                    * ax.KM_PER_BLENDER_UNIT,
                    4,
                ),
                "corner_geocentric_radius_bu": {
                    cid: round(position.length, 7) for cid, position in target_world.items()
                },
                "footprint_edges_km": [round(value, 4) for value in edges_km],
                "beams": beam_errors,
                "satellite_world": [round(v, 5) for v in satellite_world],
                "sweep_position": sweep_value,
            }
        )

    radius_tolerance_m = max(
        RADIUS_TOLERANCE_FLOOR_M, RADIUS_TOLERANCE_RELATIVE * earth_radius_km * 1000.0
    )
    max_beam_length_m = max(
        beam["length_km"] * 1000.0 for entry in per_frame for beam in entry["beams"].values()
    )
    beam_tolerance_m = max(
        BEAM_TOLERANCE_FLOOR_M, BEAM_TOLERANCE_RELATIVE * max_beam_length_m
    )

    max_radius = max(entry["max_radius_deviation_m"] for entry in per_frame)
    max_tip = max(
        beam["tip_to_corner_m"] for entry in per_frame for beam in entry["beams"].values()
    )
    max_root = max(
        beam["root_to_satellite_m"] for entry in per_frame for beam in entry["beams"].values()
    )

    all_edges = [value for entry in per_frame for value in entry["footprint_edges_km"]]
    edge_spread_km = max(all_edges) - min(all_edges)

    sweep_values = [
        entry["sweep_position"] for entry in per_frame if entry["sweep_position"] is not None
    ]
    sweep_monotonic = all(
        b >= a - 1e-9 for a, b in zip(sweep_values, sweep_values[1:])
    )

    checks = {
        "aoi_on_configured_sphere": max_radius <= radius_tolerance_m,
        "beam_tips_registered_to_corners": max_tip <= beam_tolerance_m,
        "beam_roots_registered_to_satellite": max_root <= beam_tolerance_m,
        "footprint_identity_preserved": edge_spread_km <= 0.5,
        "sweep_travels_monotonically": sweep_monotonic,
    }

    return {
        "scene": scene_id,
        "fixture": description["fixture_id"],
        "fixture_config": {
            key: fixture[key]
            for key in (
                "center_lat_deg",
                "center_lon_deg",
                "span_km",
                "bearing_deg",
                "surface_offset_m",
                "edge_samples",
                "fill_grid",
            )
        },
        "classification": scene_config["aoi_injection_interface"]["classification"],
        "earth_radius_km": earth_radius_km,
        "surface_radius_bu": round(surface_radius_bu, 8),
        "corner_lock_radius_bu": round(lock_radius_bu, 8),
        "longitude_offset_deg": description["longitude_offset_deg"],
        "corner_geographic": [
            [round(lat, 5), round(lon, 5)] for lat, lon in description["corner_geographic"]
        ],
        "boundary_sample_count": len(description["boundary_units"]),
        "boundary_sample_spacing_km": round(ax.boundary_sample_spacing_km(description), 4),
        "max_chord_sagitta_km": round(ax.max_chord_sagitta_km(description), 6),
        "tolerances": {
            "radius_m": round(radius_tolerance_m, 5),
            "beam_endpoint_m": round(beam_tolerance_m, 5),
            "basis": "absolute floor plus a relative term sized to single-precision "
            "transform error at planetary scale; see the module header",
        },
        "summary": {
            "max_radius_deviation_m": round(max_radius, 5),
            "max_beam_tip_error_m": round(max_tip, 5),
            "max_beam_root_error_m": round(max_root, 5),
            "footprint_edge_spread_km": round(edge_spread_km, 5),
        },
        "checks": checks,
        "passed": all(checks.values()),
        "frames": per_frame,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit built AOI geometry in world space.")
    parser.add_argument("--scene", default="hero_aoi_acquisition")
    parser.add_argument("--aoi-fixture", default=None)
    parser.add_argument(
        "--frames",
        default="1,60,120,156,170,190,205,220,240",
        help="comma-separated frames to audit",
    )
    parser.add_argument("--out", default=None, help="write the audit record as JSON")
    args = parser.parse_args(hc.argv_after_double_dash())

    frames = [int(value) for value in args.frames.split(",") if value.strip()]
    record = audit(args.scene, args.aoi_fixture, frames)

    print(json.dumps(record, indent=2))
    if args.out:
        out = Path(args.out)
        hc.ensure_dir(out.parent)
        out.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
        print("[hero] AOI audit -> " + hc.relpath(out))

    print("[hero] AOI audit " + ("PASSED" if record["passed"] else "FAILED"))
    if not record["passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
